# Generated by Django 4.2.5 on 2023-09-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventoryUpdateOrigin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventoryUpdateOriginDate',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
